
var res = {
	loading:"res/loading.js",
baseButton:"res/UI/baseButton.png",
cardGroup:"res/UI/cardGroup.png",
cardGroupSingle:"res/UI/cardGroupSingle.png",
loading:"res/UI/loading.png",
cardHandBack:"res/Card/Little/cardHandBack.png",
sk1002:"res/Card/Little/sk1002.png",
kakuang:"res/Card/Base/kakuang.png",
kaGJL:"res/Card/Base/kaGJL.png",
kadi:"res/Card/Base/kadi.png",
kaT_FJ:"res/Card/Base/kaT_FJ.png",
kaditiao:"res/Card/Base/kaditiao.png",
kaSMZ:"res/Card/Base/kaSMZ.png",
kaFY:"res/Card/Base/kaFY.png",
katiao:"res/Card/Base/katiao.png",
kaYDL:"res/Card/Base/kaYDL.png",
gw1002:"res/Card/monster/gw1002.png",
monsterDefault:"res/Card/monster/monsterDefault.png",
iconLeftArrow:"res/Other/iconLeftArrow.png",
energy:"res/Other/energy.png",
god:"res/Other/god.png",
iconDownArrow:"res/Other/iconDownArrow.png",
redHeart:"res/Other/redHeart.png",
gold16_z2x:"res/Other/Gold/gold16_z2x.png",
gold16_f2x:"res/Other/Gold/gold16_f2x.png",
gold16z:"res/Other/Gold/gold16z.png",
gold16f:"res/Other/Gold/gold16f.png",
PortTown022:"res/Map/PortTown022.png",
chessMap5x5:"res/Map/chessMap5x5.tmx",
blackFire2xplist:"res/Particle/blackFire2xplist.plist",
piantouAnimpng:"res/Particle/piantouAnimpng.png",
particleTexture:"res/Particle/particleTexture.png",
blackFirepng:"res/Particle/blackFirepng.png",
blackFireplist:"res/Particle/blackFireplist.plist",
piantouAnimplist:"res/Particle/piantouAnimplist.plist",
blackFire2xpng:"res/Particle/blackFire2xpng.png",
monster26:"res/piece/monster26.plist",
monster26:"res/piece/monster26.png",
qz1001:"res/piece/monster/qz1001.png",
picon1001:"res/piece/building/picon1001.png",
picon1000:"res/piece/building/picon1000.png",

	};
var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
	
